name: evlow_foodies
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  auto_route: ^8.2.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.2.1
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0

flutter:

  uses-material-design: true

  assets:
   - images/
  fonts:
    - family: AdventPro
      fonts:
        - asset: fonts/AdventPro-Medium.ttf
    
 