// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6iDRVLu3AnF5DYT49zuBbivQRvg4W0A',
    appId: '1:773382484480:web:2ecd113cca3c32a6569ee5',
    messagingSenderId: '773382484480',
    projectId: 'evlow-foodies-bc520',
    authDomain: 'evlow-foodies-bc520.firebaseapp.com',
    storageBucket: 'evlow-foodies-bc520.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSZ82deliZewxWtl2QMKysCxsbdXuSDoA',
    appId: '1:773382484480:android:29958f74e2dfa9a3569ee5',
    messagingSenderId: '773382484480',
    projectId: 'evlow-foodies-bc520',
    storageBucket: 'evlow-foodies-bc520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAus-J7y9HZ5BY4Qi3OIuNNAOVrsAtmQkk',
    appId: '1:773382484480:ios:23d7179ef4618b54569ee5',
    messagingSenderId: '773382484480',
    projectId: 'evlow-foodies-bc520',
    storageBucket: 'evlow-foodies-bc520.appspot.com',
    iosBundleId: 'com.example.evlowFoodies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAus-J7y9HZ5BY4Qi3OIuNNAOVrsAtmQkk',
    appId: '1:773382484480:ios:23d7179ef4618b54569ee5',
    messagingSenderId: '773382484480',
    projectId: 'evlow-foodies-bc520',
    storageBucket: 'evlow-foodies-bc520.appspot.com',
    iosBundleId: 'com.example.evlowFoodies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6iDRVLu3AnF5DYT49zuBbivQRvg4W0A',
    appId: '1:773382484480:web:7a00a4fc8a34bdac569ee5',
    messagingSenderId: '773382484480',
    projectId: 'evlow-foodies-bc520',
    authDomain: 'evlow-foodies-bc520.firebaseapp.com',
    storageBucket: 'evlow-foodies-bc520.appspot.com',
  );
}
